### ISSUE TITLE
numguess 게임 만들기

### ISSUE THREAD

**Issue by sseungki98** [geonxee/numguess#1]
## 요약
사용자로부터 이름과 추측을 얻어낸다.

## TODO LIST 😄 
- [x] 사용자에게 이름을 입력 받는다.
- [x] 입력받은 이름으로 환영 인사를 건넨다 🤝 
- [x] 1에서 100 사이의 랜덤한 정답을 생성하고 출력한다.
- [x] 사용자에게 추측을 받아낸다.
- [x] 받아낸 추측 값을 출력한다.
- [x] 추측값이 정답과 같으면 True, 아니라면 False를 출력한다.
